words: kurza twarza,kurka,cholera,błyskawica

mappingDays:
  Monday: poniedzialek
  Tuesday: wtorek
  Wednesday: sroda
  Thursday: czwartek
  Friday: piatek
  Saturday: sobota
  Sunday: niedziela

my:
patterns:
  - "(\\d{3})(\\d{3})(\\d{3})"
  - "(\\d{2})(\\d{3})(\\d{4})"